import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing/Navbar";
import CartHydration from "@/components/landing/cart-hydration";
import { Toaster } from 'react-hot-toast';


const poppins = Poppins({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400"], // O los pesos que necesites, por ejemplo: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${poppins.variable} antialiased overflow-x-hidden`}
      >
        <CartHydration />
        <Navbar />
        <main className="mt-32">

          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
